### ISSUE TITLE
درخواست ایجاد دکمه "ذخیره و ارسال به مشتری" در انتهای ثبت (پیش) فاکتور

### ISSUE THREAD

**Issue by hgolmohammadi** [jafarzadeh/Accounting#38]
در بخش تعریف پیش فاکتور در قسمت پایانی اطلاعات محصول، دکمه « ارسال به مشتری» در بخش پایین در کنار گزینه «ذخیره» گنجانده شود.

**Comment by mehabadi** [comment]
@jafarzadeh نیازمند سرویس جدید

**Comment by hgolmohammadi** [comment]
صرفا عمل ذخیره انجام شده و همچنان ارسال به مشتری صورت نمی پذیرد
